
trigger:
- master

jobs:
- job: Build1
  displayName: Build BIOS Core
  
  #Image which has Visual Studio 2017 installed on Windows Server 2016.
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'vs2017-win2016'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - script: |
        python --version
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
      displayName: Install/Upgrade pip