
trigger:
- master

jobs:
- job: Build1
  displayName: Build BIOS Core
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'vs2017-win2016'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - script: |
        python3 --version
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
    displayName: Install Python components